FROM node:22.18.0-alpine3.22

LABEL name=jobman-k8s-logger
LABEL authors="Andy S Alic (asalic)"

COPY jest.config.* package.json tsconfig.json /opt/jobman/
COPY src /opt/jobman/src
COPY bin /opt/jobman/bin

RUN cd /opt/jobman/ \
    && npm install \
    && npx tsc \
    && npm prune --production \
    && ln -s /opt/jobman/bin/jobman-k8s-logger /usr/bin/ \
    && chmod +x /opt/jobman/bin/jobman-k8s-logger \
    && addgroup -S jobman && adduser -G jobman -S jobman

# Set this dynamically via k8s when using the image with a container
ENV POD_NAME ''
# Set this dynamically via k8s when using the image with a container
ENV POD_NAMESPACE ''

USER jobman

ENTRYPOINT ["jobman-k8s-logger"]